# Generated by Django 5.2.6 on 2025-11-28 15:48

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_id_alter_orderitem_id'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address_line1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address_line2',
            new_name='address2',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='shipment',
            name='label_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.shippingaddress'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_shipment', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_shippingaddress', to='orders.order'),
        ),
    ]
